services:
  db:
    image: postgres:18
    container_name: postgres-maintenance-bpdr-service
    environment:
      POSTGRES_USER: bpdr
      POSTGRES_PASSWORD: bpdr_maintenance
      POSTGRES_DB: maintenance-bpdr-service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: