
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const MachineStatus = {
  OPERATIONAL: 'OPERATIONAL',
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
  DECOMMISSIONED: 'DECOMMISSIONED'
} as const

export type MachineStatus = (typeof MachineStatus)[keyof typeof MachineStatus]


export const MaintenanceType = {
  PREVENTIVE: 'PREVENTIVE',
  CORRECTIVE: 'CORRECTIVE',
  INSPECTION: 'INSPECTION'
} as const

export type MaintenanceType = (typeof MaintenanceType)[keyof typeof MaintenanceType]


export const MaintenanceLogStatus = {
  OPEN: 'OPEN',
  COMPLETED: 'COMPLETED'
} as const

export type MaintenanceLogStatus = (typeof MaintenanceLogStatus)[keyof typeof MaintenanceLogStatus]
