
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MaintenanceLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model MaintenanceLog
 * 
 */
export type MaintenanceLogModel = runtime.Types.Result.DefaultSelection<Prisma.$MaintenanceLogPayload>

export type AggregateMaintenanceLog = {
  _count: MaintenanceLogCountAggregateOutputType | null
  _avg: MaintenanceLogAvgAggregateOutputType | null
  _sum: MaintenanceLogSumAggregateOutputType | null
  _min: MaintenanceLogMinAggregateOutputType | null
  _max: MaintenanceLogMaxAggregateOutputType | null
}

export type MaintenanceLogAvgAggregateOutputType = {
  id: number | null
  machineId: number | null
  technicianId: number | null
}

export type MaintenanceLogSumAggregateOutputType = {
  id: number | null
  machineId: number | null
  technicianId: number | null
}

export type MaintenanceLogMinAggregateOutputType = {
  id: number | null
  machineId: number | null
  technicianId: number | null
  type: $Enums.MaintenanceType | null
  description: string | null
  status: $Enums.MaintenanceLogStatus | null
  startedAt: Date | null
  completedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MaintenanceLogMaxAggregateOutputType = {
  id: number | null
  machineId: number | null
  technicianId: number | null
  type: $Enums.MaintenanceType | null
  description: string | null
  status: $Enums.MaintenanceLogStatus | null
  startedAt: Date | null
  completedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MaintenanceLogCountAggregateOutputType = {
  id: number
  machineId: number
  technicianId: number
  type: number
  description: number
  status: number
  startedAt: number
  completedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MaintenanceLogAvgAggregateInputType = {
  id?: true
  machineId?: true
  technicianId?: true
}

export type MaintenanceLogSumAggregateInputType = {
  id?: true
  machineId?: true
  technicianId?: true
}

export type MaintenanceLogMinAggregateInputType = {
  id?: true
  machineId?: true
  technicianId?: true
  type?: true
  description?: true
  status?: true
  startedAt?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type MaintenanceLogMaxAggregateInputType = {
  id?: true
  machineId?: true
  technicianId?: true
  type?: true
  description?: true
  status?: true
  startedAt?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type MaintenanceLogCountAggregateInputType = {
  id?: true
  machineId?: true
  technicianId?: true
  type?: true
  description?: true
  status?: true
  startedAt?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MaintenanceLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MaintenanceLog to aggregate.
   */
  where?: Prisma.MaintenanceLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaintenanceLogs to fetch.
   */
  orderBy?: Prisma.MaintenanceLogOrderByWithRelationInput | Prisma.MaintenanceLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MaintenanceLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaintenanceLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaintenanceLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MaintenanceLogs
  **/
  _count?: true | MaintenanceLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MaintenanceLogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MaintenanceLogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MaintenanceLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MaintenanceLogMaxAggregateInputType
}

export type GetMaintenanceLogAggregateType<T extends MaintenanceLogAggregateArgs> = {
      [P in keyof T & keyof AggregateMaintenanceLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMaintenanceLog[P]>
    : Prisma.GetScalarType<T[P], AggregateMaintenanceLog[P]>
}




export type MaintenanceLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MaintenanceLogWhereInput
  orderBy?: Prisma.MaintenanceLogOrderByWithAggregationInput | Prisma.MaintenanceLogOrderByWithAggregationInput[]
  by: Prisma.MaintenanceLogScalarFieldEnum[] | Prisma.MaintenanceLogScalarFieldEnum
  having?: Prisma.MaintenanceLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MaintenanceLogCountAggregateInputType | true
  _avg?: MaintenanceLogAvgAggregateInputType
  _sum?: MaintenanceLogSumAggregateInputType
  _min?: MaintenanceLogMinAggregateInputType
  _max?: MaintenanceLogMaxAggregateInputType
}

export type MaintenanceLogGroupByOutputType = {
  id: number
  machineId: number
  technicianId: number
  type: $Enums.MaintenanceType
  description: string
  status: $Enums.MaintenanceLogStatus
  startedAt: Date
  completedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: MaintenanceLogCountAggregateOutputType | null
  _avg: MaintenanceLogAvgAggregateOutputType | null
  _sum: MaintenanceLogSumAggregateOutputType | null
  _min: MaintenanceLogMinAggregateOutputType | null
  _max: MaintenanceLogMaxAggregateOutputType | null
}

export type GetMaintenanceLogGroupByPayload<T extends MaintenanceLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MaintenanceLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MaintenanceLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MaintenanceLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MaintenanceLogGroupByOutputType[P]>
      }
    >
  >



export type MaintenanceLogWhereInput = {
  AND?: Prisma.MaintenanceLogWhereInput | Prisma.MaintenanceLogWhereInput[]
  OR?: Prisma.MaintenanceLogWhereInput[]
  NOT?: Prisma.MaintenanceLogWhereInput | Prisma.MaintenanceLogWhereInput[]
  id?: Prisma.IntFilter<"MaintenanceLog"> | number
  machineId?: Prisma.IntFilter<"MaintenanceLog"> | number
  technicianId?: Prisma.IntFilter<"MaintenanceLog"> | number
  type?: Prisma.EnumMaintenanceTypeFilter<"MaintenanceLog"> | $Enums.MaintenanceType
  description?: Prisma.StringFilter<"MaintenanceLog"> | string
  status?: Prisma.EnumMaintenanceLogStatusFilter<"MaintenanceLog"> | $Enums.MaintenanceLogStatus
  startedAt?: Prisma.DateTimeFilter<"MaintenanceLog"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"MaintenanceLog"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"MaintenanceLog"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MaintenanceLog"> | Date | string
  machine?: Prisma.XOR<Prisma.MachineScalarRelationFilter, Prisma.MachineWhereInput>
  partsUsed?: Prisma.PartUsageListRelationFilter
  photos?: Prisma.PhotoListRelationFilter
}

export type MaintenanceLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  machineId?: Prisma.SortOrder
  technicianId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  machine?: Prisma.MachineOrderByWithRelationInput
  partsUsed?: Prisma.PartUsageOrderByRelationAggregateInput
  photos?: Prisma.PhotoOrderByRelationAggregateInput
}

export type MaintenanceLogWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.MaintenanceLogWhereInput | Prisma.MaintenanceLogWhereInput[]
  OR?: Prisma.MaintenanceLogWhereInput[]
  NOT?: Prisma.MaintenanceLogWhereInput | Prisma.MaintenanceLogWhereInput[]
  machineId?: Prisma.IntFilter<"MaintenanceLog"> | number
  technicianId?: Prisma.IntFilter<"MaintenanceLog"> | number
  type?: Prisma.EnumMaintenanceTypeFilter<"MaintenanceLog"> | $Enums.MaintenanceType
  description?: Prisma.StringFilter<"MaintenanceLog"> | string
  status?: Prisma.EnumMaintenanceLogStatusFilter<"MaintenanceLog"> | $Enums.MaintenanceLogStatus
  startedAt?: Prisma.DateTimeFilter<"MaintenanceLog"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"MaintenanceLog"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"MaintenanceLog"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MaintenanceLog"> | Date | string
  machine?: Prisma.XOR<Prisma.MachineScalarRelationFilter, Prisma.MachineWhereInput>
  partsUsed?: Prisma.PartUsageListRelationFilter
  photos?: Prisma.PhotoListRelationFilter
}, "id">

export type MaintenanceLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  machineId?: Prisma.SortOrder
  technicianId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MaintenanceLogCountOrderByAggregateInput
  _avg?: Prisma.MaintenanceLogAvgOrderByAggregateInput
  _max?: Prisma.MaintenanceLogMaxOrderByAggregateInput
  _min?: Prisma.MaintenanceLogMinOrderByAggregateInput
  _sum?: Prisma.MaintenanceLogSumOrderByAggregateInput
}

export type MaintenanceLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.MaintenanceLogScalarWhereWithAggregatesInput | Prisma.MaintenanceLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.MaintenanceLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MaintenanceLogScalarWhereWithAggregatesInput | Prisma.MaintenanceLogScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"MaintenanceLog"> | number
  machineId?: Prisma.IntWithAggregatesFilter<"MaintenanceLog"> | number
  technicianId?: Prisma.IntWithAggregatesFilter<"MaintenanceLog"> | number
  type?: Prisma.EnumMaintenanceTypeWithAggregatesFilter<"MaintenanceLog"> | $Enums.MaintenanceType
  description?: Prisma.StringWithAggregatesFilter<"MaintenanceLog"> | string
  status?: Prisma.EnumMaintenanceLogStatusWithAggregatesFilter<"MaintenanceLog"> | $Enums.MaintenanceLogStatus
  startedAt?: Prisma.DateTimeWithAggregatesFilter<"MaintenanceLog"> | Date | string
  completedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"MaintenanceLog"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MaintenanceLog"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MaintenanceLog"> | Date | string
}

export type MaintenanceLogCreateInput = {
  technicianId: number
  type: $Enums.MaintenanceType
  description: string
  status?: $Enums.MaintenanceLogStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  machine: Prisma.MachineCreateNestedOneWithoutLogsInput
  partsUsed?: Prisma.PartUsageCreateNestedManyWithoutMaintenanceLogInput
  photos?: Prisma.PhotoCreateNestedManyWithoutMaintenanceLogInput
}

export type MaintenanceLogUncheckedCreateInput = {
  id?: number
  machineId: number
  technicianId: number
  type: $Enums.MaintenanceType
  description: string
  status?: $Enums.MaintenanceLogStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  partsUsed?: Prisma.PartUsageUncheckedCreateNestedManyWithoutMaintenanceLogInput
  photos?: Prisma.PhotoUncheckedCreateNestedManyWithoutMaintenanceLogInput
}

export type MaintenanceLogUpdateInput = {
  technicianId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumMaintenanceTypeFieldUpdateOperationsInput | $Enums.MaintenanceType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMaintenanceLogStatusFieldUpdateOperationsInput | $Enums.MaintenanceLogStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  machine?: Prisma.MachineUpdateOneRequiredWithoutLogsNestedInput
  partsUsed?: Prisma.PartUsageUpdateManyWithoutMaintenanceLogNestedInput
  photos?: Prisma.PhotoUpdateManyWithoutMaintenanceLogNestedInput
}

export type MaintenanceLogUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  machineId?: Prisma.IntFieldUpdateOperationsInput | number
  technicianId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumMaintenanceTypeFieldUpdateOperationsInput | $Enums.MaintenanceType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMaintenanceLogStatusFieldUpdateOperationsInput | $Enums.MaintenanceLogStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  partsUsed?: Prisma.PartUsageUncheckedUpdateManyWithoutMaintenanceLogNestedInput
  photos?: Prisma.PhotoUncheckedUpdateManyWithoutMaintenanceLogNestedInput
}

export type MaintenanceLogCreateManyInput = {
  id?: number
  machineId: number
  technicianId: number
  type: $Enums.MaintenanceType
  description: string
  status?: $Enums.MaintenanceLogStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MaintenanceLogUpdateManyMutationInput = {
  technicianId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumMaintenanceTypeFieldUpdateOperationsInput | $Enums.MaintenanceType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMaintenanceLogStatusFieldUpdateOperationsInput | $Enums.MaintenanceLogStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaintenanceLogUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  machineId?: Prisma.IntFieldUpdateOperationsInput | number
  technicianId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumMaintenanceTypeFieldUpdateOperationsInput | $Enums.MaintenanceType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMaintenanceLogStatusFieldUpdateOperationsInput | $Enums.MaintenanceLogStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaintenanceLogListRelationFilter = {
  every?: Prisma.MaintenanceLogWhereInput
  some?: Prisma.MaintenanceLogWhereInput
  none?: Prisma.MaintenanceLogWhereInput
}

export type MaintenanceLogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MaintenanceLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  machineId?: Prisma.SortOrder
  technicianId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MaintenanceLogAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  machineId?: Prisma.SortOrder
  technicianId?: Prisma.SortOrder
}

export type MaintenanceLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  machineId?: Prisma.SortOrder
  technicianId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MaintenanceLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  machineId?: Prisma.SortOrder
  technicianId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MaintenanceLogSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  machineId?: Prisma.SortOrder
  technicianId?: Prisma.SortOrder
}

export type MaintenanceLogScalarRelationFilter = {
  is?: Prisma.MaintenanceLogWhereInput
  isNot?: Prisma.MaintenanceLogWhereInput
}

export type MaintenanceLogCreateNestedManyWithoutMachineInput = {
  create?: Prisma.XOR<Prisma.MaintenanceLogCreateWithoutMachineInput, Prisma.MaintenanceLogUncheckedCreateWithoutMachineInput> | Prisma.MaintenanceLogCreateWithoutMachineInput[] | Prisma.MaintenanceLogUncheckedCreateWithoutMachineInput[]
  connectOrCreate?: Prisma.MaintenanceLogCreateOrConnectWithoutMachineInput | Prisma.MaintenanceLogCreateOrConnectWithoutMachineInput[]
  createMany?: Prisma.MaintenanceLogCreateManyMachineInputEnvelope
  connect?: Prisma.MaintenanceLogWhereUniqueInput | Prisma.MaintenanceLogWhereUniqueInput[]
}

export type MaintenanceLogUncheckedCreateNestedManyWithoutMachineInput = {
  create?: Prisma.XOR<Prisma.MaintenanceLogCreateWithoutMachineInput, Prisma.MaintenanceLogUncheckedCreateWithoutMachineInput> | Prisma.MaintenanceLogCreateWithoutMachineInput[] | Prisma.MaintenanceLogUncheckedCreateWithoutMachineInput[]
  connectOrCreate?: Prisma.MaintenanceLogCreateOrConnectWithoutMachineInput | Prisma.MaintenanceLogCreateOrConnectWithoutMachineInput[]
  createMany?: Prisma.MaintenanceLogCreateManyMachineInputEnvelope
  connect?: Prisma.MaintenanceLogWhereUniqueInput | Prisma.MaintenanceLogWhereUniqueInput[]
}

export type MaintenanceLogUpdateManyWithoutMachineNestedInput = {
  create?: Prisma.XOR<Prisma.MaintenanceLogCreateWithoutMachineInput, Prisma.MaintenanceLogUncheckedCreateWithoutMachineInput> | Prisma.MaintenanceLogCreateWithoutMachineInput[] | Prisma.MaintenanceLogUncheckedCreateWithoutMachineInput[]
  connectOrCreate?: Prisma.MaintenanceLogCreateOrConnectWithoutMachineInput | Prisma.MaintenanceLogCreateOrConnectWithoutMachineInput[]
  upsert?: Prisma.MaintenanceLogUpsertWithWhereUniqueWithoutMachineInput | Prisma.MaintenanceLogUpsertWithWhereUniqueWithoutMachineInput[]
  createMany?: Prisma.MaintenanceLogCreateManyMachineInputEnvelope
  set?: Prisma.MaintenanceLogWhereUniqueInput | Prisma.MaintenanceLogWhereUniqueInput[]
  disconnect?: Prisma.MaintenanceLogWhereUniqueInput | Prisma.MaintenanceLogWhereUniqueInput[]
  delete?: Prisma.MaintenanceLogWhereUniqueInput | Prisma.MaintenanceLogWhereUniqueInput[]
  connect?: Prisma.MaintenanceLogWhereUniqueInput | Prisma.MaintenanceLogWhereUniqueInput[]
  update?: Prisma.MaintenanceLogUpdateWithWhereUniqueWithoutMachineInput | Prisma.MaintenanceLogUpdateWithWhereUniqueWithoutMachineInput[]
  updateMany?: Prisma.MaintenanceLogUpdateManyWithWhereWithoutMachineInput | Prisma.MaintenanceLogUpdateManyWithWhereWithoutMachineInput[]
  deleteMany?: Prisma.MaintenanceLogScalarWhereInput | Prisma.MaintenanceLogScalarWhereInput[]
}

export type MaintenanceLogUncheckedUpdateManyWithoutMachineNestedInput = {
  create?: Prisma.XOR<Prisma.MaintenanceLogCreateWithoutMachineInput, Prisma.MaintenanceLogUncheckedCreateWithoutMachineInput> | Prisma.MaintenanceLogCreateWithoutMachineInput[] | Prisma.MaintenanceLogUncheckedCreateWithoutMachineInput[]
  connectOrCreate?: Prisma.MaintenanceLogCreateOrConnectWithoutMachineInput | Prisma.MaintenanceLogCreateOrConnectWithoutMachineInput[]
  upsert?: Prisma.MaintenanceLogUpsertWithWhereUniqueWithoutMachineInput | Prisma.MaintenanceLogUpsertWithWhereUniqueWithoutMachineInput[]
  createMany?: Prisma.MaintenanceLogCreateManyMachineInputEnvelope
  set?: Prisma.MaintenanceLogWhereUniqueInput | Prisma.MaintenanceLogWhereUniqueInput[]
  disconnect?: Prisma.MaintenanceLogWhereUniqueInput | Prisma.MaintenanceLogWhereUniqueInput[]
  delete?: Prisma.MaintenanceLogWhereUniqueInput | Prisma.MaintenanceLogWhereUniqueInput[]
  connect?: Prisma.MaintenanceLogWhereUniqueInput | Prisma.MaintenanceLogWhereUniqueInput[]
  update?: Prisma.MaintenanceLogUpdateWithWhereUniqueWithoutMachineInput | Prisma.MaintenanceLogUpdateWithWhereUniqueWithoutMachineInput[]
  updateMany?: Prisma.MaintenanceLogUpdateManyWithWhereWithoutMachineInput | Prisma.MaintenanceLogUpdateManyWithWhereWithoutMachineInput[]
  deleteMany?: Prisma.MaintenanceLogScalarWhereInput | Prisma.MaintenanceLogScalarWhereInput[]
}

export type EnumMaintenanceTypeFieldUpdateOperationsInput = {
  set?: $Enums.MaintenanceType
}

export type EnumMaintenanceLogStatusFieldUpdateOperationsInput = {
  set?: $Enums.MaintenanceLogStatus
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type MaintenanceLogCreateNestedOneWithoutPhotosInput = {
  create?: Prisma.XOR<Prisma.MaintenanceLogCreateWithoutPhotosInput, Prisma.MaintenanceLogUncheckedCreateWithoutPhotosInput>
  connectOrCreate?: Prisma.MaintenanceLogCreateOrConnectWithoutPhotosInput
  connect?: Prisma.MaintenanceLogWhereUniqueInput
}

export type MaintenanceLogUpdateOneRequiredWithoutPhotosNestedInput = {
  create?: Prisma.XOR<Prisma.MaintenanceLogCreateWithoutPhotosInput, Prisma.MaintenanceLogUncheckedCreateWithoutPhotosInput>
  connectOrCreate?: Prisma.MaintenanceLogCreateOrConnectWithoutPhotosInput
  upsert?: Prisma.MaintenanceLogUpsertWithoutPhotosInput
  connect?: Prisma.MaintenanceLogWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MaintenanceLogUpdateToOneWithWhereWithoutPhotosInput, Prisma.MaintenanceLogUpdateWithoutPhotosInput>, Prisma.MaintenanceLogUncheckedUpdateWithoutPhotosInput>
}

export type MaintenanceLogCreateNestedOneWithoutPartsUsedInput = {
  create?: Prisma.XOR<Prisma.MaintenanceLogCreateWithoutPartsUsedInput, Prisma.MaintenanceLogUncheckedCreateWithoutPartsUsedInput>
  connectOrCreate?: Prisma.MaintenanceLogCreateOrConnectWithoutPartsUsedInput
  connect?: Prisma.MaintenanceLogWhereUniqueInput
}

export type MaintenanceLogUpdateOneRequiredWithoutPartsUsedNestedInput = {
  create?: Prisma.XOR<Prisma.MaintenanceLogCreateWithoutPartsUsedInput, Prisma.MaintenanceLogUncheckedCreateWithoutPartsUsedInput>
  connectOrCreate?: Prisma.MaintenanceLogCreateOrConnectWithoutPartsUsedInput
  upsert?: Prisma.MaintenanceLogUpsertWithoutPartsUsedInput
  connect?: Prisma.MaintenanceLogWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MaintenanceLogUpdateToOneWithWhereWithoutPartsUsedInput, Prisma.MaintenanceLogUpdateWithoutPartsUsedInput>, Prisma.MaintenanceLogUncheckedUpdateWithoutPartsUsedInput>
}

export type MaintenanceLogCreateWithoutMachineInput = {
  technicianId: number
  type: $Enums.MaintenanceType
  description: string
  status?: $Enums.MaintenanceLogStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  partsUsed?: Prisma.PartUsageCreateNestedManyWithoutMaintenanceLogInput
  photos?: Prisma.PhotoCreateNestedManyWithoutMaintenanceLogInput
}

export type MaintenanceLogUncheckedCreateWithoutMachineInput = {
  id?: number
  technicianId: number
  type: $Enums.MaintenanceType
  description: string
  status?: $Enums.MaintenanceLogStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  partsUsed?: Prisma.PartUsageUncheckedCreateNestedManyWithoutMaintenanceLogInput
  photos?: Prisma.PhotoUncheckedCreateNestedManyWithoutMaintenanceLogInput
}

export type MaintenanceLogCreateOrConnectWithoutMachineInput = {
  where: Prisma.MaintenanceLogWhereUniqueInput
  create: Prisma.XOR<Prisma.MaintenanceLogCreateWithoutMachineInput, Prisma.MaintenanceLogUncheckedCreateWithoutMachineInput>
}

export type MaintenanceLogCreateManyMachineInputEnvelope = {
  data: Prisma.MaintenanceLogCreateManyMachineInput | Prisma.MaintenanceLogCreateManyMachineInput[]
  skipDuplicates?: boolean
}

export type MaintenanceLogUpsertWithWhereUniqueWithoutMachineInput = {
  where: Prisma.MaintenanceLogWhereUniqueInput
  update: Prisma.XOR<Prisma.MaintenanceLogUpdateWithoutMachineInput, Prisma.MaintenanceLogUncheckedUpdateWithoutMachineInput>
  create: Prisma.XOR<Prisma.MaintenanceLogCreateWithoutMachineInput, Prisma.MaintenanceLogUncheckedCreateWithoutMachineInput>
}

export type MaintenanceLogUpdateWithWhereUniqueWithoutMachineInput = {
  where: Prisma.MaintenanceLogWhereUniqueInput
  data: Prisma.XOR<Prisma.MaintenanceLogUpdateWithoutMachineInput, Prisma.MaintenanceLogUncheckedUpdateWithoutMachineInput>
}

export type MaintenanceLogUpdateManyWithWhereWithoutMachineInput = {
  where: Prisma.MaintenanceLogScalarWhereInput
  data: Prisma.XOR<Prisma.MaintenanceLogUpdateManyMutationInput, Prisma.MaintenanceLogUncheckedUpdateManyWithoutMachineInput>
}

export type MaintenanceLogScalarWhereInput = {
  AND?: Prisma.MaintenanceLogScalarWhereInput | Prisma.MaintenanceLogScalarWhereInput[]
  OR?: Prisma.MaintenanceLogScalarWhereInput[]
  NOT?: Prisma.MaintenanceLogScalarWhereInput | Prisma.MaintenanceLogScalarWhereInput[]
  id?: Prisma.IntFilter<"MaintenanceLog"> | number
  machineId?: Prisma.IntFilter<"MaintenanceLog"> | number
  technicianId?: Prisma.IntFilter<"MaintenanceLog"> | number
  type?: Prisma.EnumMaintenanceTypeFilter<"MaintenanceLog"> | $Enums.MaintenanceType
  description?: Prisma.StringFilter<"MaintenanceLog"> | string
  status?: Prisma.EnumMaintenanceLogStatusFilter<"MaintenanceLog"> | $Enums.MaintenanceLogStatus
  startedAt?: Prisma.DateTimeFilter<"MaintenanceLog"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"MaintenanceLog"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"MaintenanceLog"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MaintenanceLog"> | Date | string
}

export type MaintenanceLogCreateWithoutPhotosInput = {
  technicianId: number
  type: $Enums.MaintenanceType
  description: string
  status?: $Enums.MaintenanceLogStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  machine: Prisma.MachineCreateNestedOneWithoutLogsInput
  partsUsed?: Prisma.PartUsageCreateNestedManyWithoutMaintenanceLogInput
}

export type MaintenanceLogUncheckedCreateWithoutPhotosInput = {
  id?: number
  machineId: number
  technicianId: number
  type: $Enums.MaintenanceType
  description: string
  status?: $Enums.MaintenanceLogStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  partsUsed?: Prisma.PartUsageUncheckedCreateNestedManyWithoutMaintenanceLogInput
}

export type MaintenanceLogCreateOrConnectWithoutPhotosInput = {
  where: Prisma.MaintenanceLogWhereUniqueInput
  create: Prisma.XOR<Prisma.MaintenanceLogCreateWithoutPhotosInput, Prisma.MaintenanceLogUncheckedCreateWithoutPhotosInput>
}

export type MaintenanceLogUpsertWithoutPhotosInput = {
  update: Prisma.XOR<Prisma.MaintenanceLogUpdateWithoutPhotosInput, Prisma.MaintenanceLogUncheckedUpdateWithoutPhotosInput>
  create: Prisma.XOR<Prisma.MaintenanceLogCreateWithoutPhotosInput, Prisma.MaintenanceLogUncheckedCreateWithoutPhotosInput>
  where?: Prisma.MaintenanceLogWhereInput
}

export type MaintenanceLogUpdateToOneWithWhereWithoutPhotosInput = {
  where?: Prisma.MaintenanceLogWhereInput
  data: Prisma.XOR<Prisma.MaintenanceLogUpdateWithoutPhotosInput, Prisma.MaintenanceLogUncheckedUpdateWithoutPhotosInput>
}

export type MaintenanceLogUpdateWithoutPhotosInput = {
  technicianId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumMaintenanceTypeFieldUpdateOperationsInput | $Enums.MaintenanceType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMaintenanceLogStatusFieldUpdateOperationsInput | $Enums.MaintenanceLogStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  machine?: Prisma.MachineUpdateOneRequiredWithoutLogsNestedInput
  partsUsed?: Prisma.PartUsageUpdateManyWithoutMaintenanceLogNestedInput
}

export type MaintenanceLogUncheckedUpdateWithoutPhotosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  machineId?: Prisma.IntFieldUpdateOperationsInput | number
  technicianId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumMaintenanceTypeFieldUpdateOperationsInput | $Enums.MaintenanceType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMaintenanceLogStatusFieldUpdateOperationsInput | $Enums.MaintenanceLogStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  partsUsed?: Prisma.PartUsageUncheckedUpdateManyWithoutMaintenanceLogNestedInput
}

export type MaintenanceLogCreateWithoutPartsUsedInput = {
  technicianId: number
  type: $Enums.MaintenanceType
  description: string
  status?: $Enums.MaintenanceLogStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  machine: Prisma.MachineCreateNestedOneWithoutLogsInput
  photos?: Prisma.PhotoCreateNestedManyWithoutMaintenanceLogInput
}

export type MaintenanceLogUncheckedCreateWithoutPartsUsedInput = {
  id?: number
  machineId: number
  technicianId: number
  type: $Enums.MaintenanceType
  description: string
  status?: $Enums.MaintenanceLogStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  photos?: Prisma.PhotoUncheckedCreateNestedManyWithoutMaintenanceLogInput
}

export type MaintenanceLogCreateOrConnectWithoutPartsUsedInput = {
  where: Prisma.MaintenanceLogWhereUniqueInput
  create: Prisma.XOR<Prisma.MaintenanceLogCreateWithoutPartsUsedInput, Prisma.MaintenanceLogUncheckedCreateWithoutPartsUsedInput>
}

export type MaintenanceLogUpsertWithoutPartsUsedInput = {
  update: Prisma.XOR<Prisma.MaintenanceLogUpdateWithoutPartsUsedInput, Prisma.MaintenanceLogUncheckedUpdateWithoutPartsUsedInput>
  create: Prisma.XOR<Prisma.MaintenanceLogCreateWithoutPartsUsedInput, Prisma.MaintenanceLogUncheckedCreateWithoutPartsUsedInput>
  where?: Prisma.MaintenanceLogWhereInput
}

export type MaintenanceLogUpdateToOneWithWhereWithoutPartsUsedInput = {
  where?: Prisma.MaintenanceLogWhereInput
  data: Prisma.XOR<Prisma.MaintenanceLogUpdateWithoutPartsUsedInput, Prisma.MaintenanceLogUncheckedUpdateWithoutPartsUsedInput>
}

export type MaintenanceLogUpdateWithoutPartsUsedInput = {
  technicianId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumMaintenanceTypeFieldUpdateOperationsInput | $Enums.MaintenanceType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMaintenanceLogStatusFieldUpdateOperationsInput | $Enums.MaintenanceLogStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  machine?: Prisma.MachineUpdateOneRequiredWithoutLogsNestedInput
  photos?: Prisma.PhotoUpdateManyWithoutMaintenanceLogNestedInput
}

export type MaintenanceLogUncheckedUpdateWithoutPartsUsedInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  machineId?: Prisma.IntFieldUpdateOperationsInput | number
  technicianId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumMaintenanceTypeFieldUpdateOperationsInput | $Enums.MaintenanceType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMaintenanceLogStatusFieldUpdateOperationsInput | $Enums.MaintenanceLogStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  photos?: Prisma.PhotoUncheckedUpdateManyWithoutMaintenanceLogNestedInput
}

export type MaintenanceLogCreateManyMachineInput = {
  id?: number
  technicianId: number
  type: $Enums.MaintenanceType
  description: string
  status?: $Enums.MaintenanceLogStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MaintenanceLogUpdateWithoutMachineInput = {
  technicianId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumMaintenanceTypeFieldUpdateOperationsInput | $Enums.MaintenanceType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMaintenanceLogStatusFieldUpdateOperationsInput | $Enums.MaintenanceLogStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  partsUsed?: Prisma.PartUsageUpdateManyWithoutMaintenanceLogNestedInput
  photos?: Prisma.PhotoUpdateManyWithoutMaintenanceLogNestedInput
}

export type MaintenanceLogUncheckedUpdateWithoutMachineInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  technicianId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumMaintenanceTypeFieldUpdateOperationsInput | $Enums.MaintenanceType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMaintenanceLogStatusFieldUpdateOperationsInput | $Enums.MaintenanceLogStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  partsUsed?: Prisma.PartUsageUncheckedUpdateManyWithoutMaintenanceLogNestedInput
  photos?: Prisma.PhotoUncheckedUpdateManyWithoutMaintenanceLogNestedInput
}

export type MaintenanceLogUncheckedUpdateManyWithoutMachineInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  technicianId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumMaintenanceTypeFieldUpdateOperationsInput | $Enums.MaintenanceType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMaintenanceLogStatusFieldUpdateOperationsInput | $Enums.MaintenanceLogStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type MaintenanceLogCountOutputType
 */

export type MaintenanceLogCountOutputType = {
  partsUsed: number
  photos: number
}

export type MaintenanceLogCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  partsUsed?: boolean | MaintenanceLogCountOutputTypeCountPartsUsedArgs
  photos?: boolean | MaintenanceLogCountOutputTypeCountPhotosArgs
}

/**
 * MaintenanceLogCountOutputType without action
 */
export type MaintenanceLogCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceLogCountOutputType
   */
  select?: Prisma.MaintenanceLogCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MaintenanceLogCountOutputType without action
 */
export type MaintenanceLogCountOutputTypeCountPartsUsedArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PartUsageWhereInput
}

/**
 * MaintenanceLogCountOutputType without action
 */
export type MaintenanceLogCountOutputTypeCountPhotosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PhotoWhereInput
}


export type MaintenanceLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  machineId?: boolean
  technicianId?: boolean
  type?: boolean
  description?: boolean
  status?: boolean
  startedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
  partsUsed?: boolean | Prisma.MaintenanceLog$partsUsedArgs<ExtArgs>
  photos?: boolean | Prisma.MaintenanceLog$photosArgs<ExtArgs>
  _count?: boolean | Prisma.MaintenanceLogCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["maintenanceLog"]>

export type MaintenanceLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  machineId?: boolean
  technicianId?: boolean
  type?: boolean
  description?: boolean
  status?: boolean
  startedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
}, ExtArgs["result"]["maintenanceLog"]>

export type MaintenanceLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  machineId?: boolean
  technicianId?: boolean
  type?: boolean
  description?: boolean
  status?: boolean
  startedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
}, ExtArgs["result"]["maintenanceLog"]>

export type MaintenanceLogSelectScalar = {
  id?: boolean
  machineId?: boolean
  technicianId?: boolean
  type?: boolean
  description?: boolean
  status?: boolean
  startedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MaintenanceLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "machineId" | "technicianId" | "type" | "description" | "status" | "startedAt" | "completedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["maintenanceLog"]>
export type MaintenanceLogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
  partsUsed?: boolean | Prisma.MaintenanceLog$partsUsedArgs<ExtArgs>
  photos?: boolean | Prisma.MaintenanceLog$photosArgs<ExtArgs>
  _count?: boolean | Prisma.MaintenanceLogCountOutputTypeDefaultArgs<ExtArgs>
}
export type MaintenanceLogIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
}
export type MaintenanceLogIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
}

export type $MaintenanceLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MaintenanceLog"
  objects: {
    machine: Prisma.$MachinePayload<ExtArgs>
    partsUsed: Prisma.$PartUsagePayload<ExtArgs>[]
    photos: Prisma.$PhotoPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    machineId: number
    technicianId: number
    type: $Enums.MaintenanceType
    description: string
    status: $Enums.MaintenanceLogStatus
    startedAt: Date
    completedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["maintenanceLog"]>
  composites: {}
}

export type MaintenanceLogGetPayload<S extends boolean | null | undefined | MaintenanceLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MaintenanceLogPayload, S>

export type MaintenanceLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MaintenanceLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MaintenanceLogCountAggregateInputType | true
  }

export interface MaintenanceLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MaintenanceLog'], meta: { name: 'MaintenanceLog' } }
  /**
   * Find zero or one MaintenanceLog that matches the filter.
   * @param {MaintenanceLogFindUniqueArgs} args - Arguments to find a MaintenanceLog
   * @example
   * // Get one MaintenanceLog
   * const maintenanceLog = await prisma.maintenanceLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MaintenanceLogFindUniqueArgs>(args: Prisma.SelectSubset<T, MaintenanceLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MaintenanceLogClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MaintenanceLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MaintenanceLogFindUniqueOrThrowArgs} args - Arguments to find a MaintenanceLog
   * @example
   * // Get one MaintenanceLog
   * const maintenanceLog = await prisma.maintenanceLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MaintenanceLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MaintenanceLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MaintenanceLogClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MaintenanceLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceLogFindFirstArgs} args - Arguments to find a MaintenanceLog
   * @example
   * // Get one MaintenanceLog
   * const maintenanceLog = await prisma.maintenanceLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MaintenanceLogFindFirstArgs>(args?: Prisma.SelectSubset<T, MaintenanceLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__MaintenanceLogClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MaintenanceLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceLogFindFirstOrThrowArgs} args - Arguments to find a MaintenanceLog
   * @example
   * // Get one MaintenanceLog
   * const maintenanceLog = await prisma.maintenanceLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MaintenanceLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MaintenanceLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MaintenanceLogClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MaintenanceLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MaintenanceLogs
   * const maintenanceLogs = await prisma.maintenanceLog.findMany()
   * 
   * // Get first 10 MaintenanceLogs
   * const maintenanceLogs = await prisma.maintenanceLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const maintenanceLogWithIdOnly = await prisma.maintenanceLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MaintenanceLogFindManyArgs>(args?: Prisma.SelectSubset<T, MaintenanceLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaintenanceLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MaintenanceLog.
   * @param {MaintenanceLogCreateArgs} args - Arguments to create a MaintenanceLog.
   * @example
   * // Create one MaintenanceLog
   * const MaintenanceLog = await prisma.maintenanceLog.create({
   *   data: {
   *     // ... data to create a MaintenanceLog
   *   }
   * })
   * 
   */
  create<T extends MaintenanceLogCreateArgs>(args: Prisma.SelectSubset<T, MaintenanceLogCreateArgs<ExtArgs>>): Prisma.Prisma__MaintenanceLogClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MaintenanceLogs.
   * @param {MaintenanceLogCreateManyArgs} args - Arguments to create many MaintenanceLogs.
   * @example
   * // Create many MaintenanceLogs
   * const maintenanceLog = await prisma.maintenanceLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MaintenanceLogCreateManyArgs>(args?: Prisma.SelectSubset<T, MaintenanceLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MaintenanceLogs and returns the data saved in the database.
   * @param {MaintenanceLogCreateManyAndReturnArgs} args - Arguments to create many MaintenanceLogs.
   * @example
   * // Create many MaintenanceLogs
   * const maintenanceLog = await prisma.maintenanceLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MaintenanceLogs and only return the `id`
   * const maintenanceLogWithIdOnly = await prisma.maintenanceLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MaintenanceLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MaintenanceLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaintenanceLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MaintenanceLog.
   * @param {MaintenanceLogDeleteArgs} args - Arguments to delete one MaintenanceLog.
   * @example
   * // Delete one MaintenanceLog
   * const MaintenanceLog = await prisma.maintenanceLog.delete({
   *   where: {
   *     // ... filter to delete one MaintenanceLog
   *   }
   * })
   * 
   */
  delete<T extends MaintenanceLogDeleteArgs>(args: Prisma.SelectSubset<T, MaintenanceLogDeleteArgs<ExtArgs>>): Prisma.Prisma__MaintenanceLogClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MaintenanceLog.
   * @param {MaintenanceLogUpdateArgs} args - Arguments to update one MaintenanceLog.
   * @example
   * // Update one MaintenanceLog
   * const maintenanceLog = await prisma.maintenanceLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MaintenanceLogUpdateArgs>(args: Prisma.SelectSubset<T, MaintenanceLogUpdateArgs<ExtArgs>>): Prisma.Prisma__MaintenanceLogClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MaintenanceLogs.
   * @param {MaintenanceLogDeleteManyArgs} args - Arguments to filter MaintenanceLogs to delete.
   * @example
   * // Delete a few MaintenanceLogs
   * const { count } = await prisma.maintenanceLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MaintenanceLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, MaintenanceLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MaintenanceLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MaintenanceLogs
   * const maintenanceLog = await prisma.maintenanceLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MaintenanceLogUpdateManyArgs>(args: Prisma.SelectSubset<T, MaintenanceLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MaintenanceLogs and returns the data updated in the database.
   * @param {MaintenanceLogUpdateManyAndReturnArgs} args - Arguments to update many MaintenanceLogs.
   * @example
   * // Update many MaintenanceLogs
   * const maintenanceLog = await prisma.maintenanceLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MaintenanceLogs and only return the `id`
   * const maintenanceLogWithIdOnly = await prisma.maintenanceLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MaintenanceLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MaintenanceLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaintenanceLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MaintenanceLog.
   * @param {MaintenanceLogUpsertArgs} args - Arguments to update or create a MaintenanceLog.
   * @example
   * // Update or create a MaintenanceLog
   * const maintenanceLog = await prisma.maintenanceLog.upsert({
   *   create: {
   *     // ... data to create a MaintenanceLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MaintenanceLog we want to update
   *   }
   * })
   */
  upsert<T extends MaintenanceLogUpsertArgs>(args: Prisma.SelectSubset<T, MaintenanceLogUpsertArgs<ExtArgs>>): Prisma.Prisma__MaintenanceLogClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MaintenanceLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceLogCountArgs} args - Arguments to filter MaintenanceLogs to count.
   * @example
   * // Count the number of MaintenanceLogs
   * const count = await prisma.maintenanceLog.count({
   *   where: {
   *     // ... the filter for the MaintenanceLogs we want to count
   *   }
   * })
  **/
  count<T extends MaintenanceLogCountArgs>(
    args?: Prisma.Subset<T, MaintenanceLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MaintenanceLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MaintenanceLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MaintenanceLogAggregateArgs>(args: Prisma.Subset<T, MaintenanceLogAggregateArgs>): Prisma.PrismaPromise<GetMaintenanceLogAggregateType<T>>

  /**
   * Group by MaintenanceLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MaintenanceLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MaintenanceLogGroupByArgs['orderBy'] }
      : { orderBy?: MaintenanceLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MaintenanceLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMaintenanceLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MaintenanceLog model
 */
readonly fields: MaintenanceLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MaintenanceLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MaintenanceLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  machine<T extends Prisma.MachineDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MachineDefaultArgs<ExtArgs>>): Prisma.Prisma__MachineClient<runtime.Types.Result.GetResult<Prisma.$MachinePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  partsUsed<T extends Prisma.MaintenanceLog$partsUsedArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MaintenanceLog$partsUsedArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PartUsagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  photos<T extends Prisma.MaintenanceLog$photosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MaintenanceLog$photosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PhotoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MaintenanceLog model
 */
export interface MaintenanceLogFieldRefs {
  readonly id: Prisma.FieldRef<"MaintenanceLog", 'Int'>
  readonly machineId: Prisma.FieldRef<"MaintenanceLog", 'Int'>
  readonly technicianId: Prisma.FieldRef<"MaintenanceLog", 'Int'>
  readonly type: Prisma.FieldRef<"MaintenanceLog", 'MaintenanceType'>
  readonly description: Prisma.FieldRef<"MaintenanceLog", 'String'>
  readonly status: Prisma.FieldRef<"MaintenanceLog", 'MaintenanceLogStatus'>
  readonly startedAt: Prisma.FieldRef<"MaintenanceLog", 'DateTime'>
  readonly completedAt: Prisma.FieldRef<"MaintenanceLog", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"MaintenanceLog", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"MaintenanceLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MaintenanceLog findUnique
 */
export type MaintenanceLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceLog
   */
  select?: Prisma.MaintenanceLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceLog
   */
  omit?: Prisma.MaintenanceLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceLogInclude<ExtArgs> | null
  /**
   * Filter, which MaintenanceLog to fetch.
   */
  where: Prisma.MaintenanceLogWhereUniqueInput
}

/**
 * MaintenanceLog findUniqueOrThrow
 */
export type MaintenanceLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceLog
   */
  select?: Prisma.MaintenanceLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceLog
   */
  omit?: Prisma.MaintenanceLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceLogInclude<ExtArgs> | null
  /**
   * Filter, which MaintenanceLog to fetch.
   */
  where: Prisma.MaintenanceLogWhereUniqueInput
}

/**
 * MaintenanceLog findFirst
 */
export type MaintenanceLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceLog
   */
  select?: Prisma.MaintenanceLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceLog
   */
  omit?: Prisma.MaintenanceLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceLogInclude<ExtArgs> | null
  /**
   * Filter, which MaintenanceLog to fetch.
   */
  where?: Prisma.MaintenanceLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaintenanceLogs to fetch.
   */
  orderBy?: Prisma.MaintenanceLogOrderByWithRelationInput | Prisma.MaintenanceLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MaintenanceLogs.
   */
  cursor?: Prisma.MaintenanceLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaintenanceLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaintenanceLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MaintenanceLogs.
   */
  distinct?: Prisma.MaintenanceLogScalarFieldEnum | Prisma.MaintenanceLogScalarFieldEnum[]
}

/**
 * MaintenanceLog findFirstOrThrow
 */
export type MaintenanceLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceLog
   */
  select?: Prisma.MaintenanceLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceLog
   */
  omit?: Prisma.MaintenanceLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceLogInclude<ExtArgs> | null
  /**
   * Filter, which MaintenanceLog to fetch.
   */
  where?: Prisma.MaintenanceLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaintenanceLogs to fetch.
   */
  orderBy?: Prisma.MaintenanceLogOrderByWithRelationInput | Prisma.MaintenanceLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MaintenanceLogs.
   */
  cursor?: Prisma.MaintenanceLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaintenanceLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaintenanceLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MaintenanceLogs.
   */
  distinct?: Prisma.MaintenanceLogScalarFieldEnum | Prisma.MaintenanceLogScalarFieldEnum[]
}

/**
 * MaintenanceLog findMany
 */
export type MaintenanceLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceLog
   */
  select?: Prisma.MaintenanceLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceLog
   */
  omit?: Prisma.MaintenanceLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceLogInclude<ExtArgs> | null
  /**
   * Filter, which MaintenanceLogs to fetch.
   */
  where?: Prisma.MaintenanceLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaintenanceLogs to fetch.
   */
  orderBy?: Prisma.MaintenanceLogOrderByWithRelationInput | Prisma.MaintenanceLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MaintenanceLogs.
   */
  cursor?: Prisma.MaintenanceLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaintenanceLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaintenanceLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MaintenanceLogs.
   */
  distinct?: Prisma.MaintenanceLogScalarFieldEnum | Prisma.MaintenanceLogScalarFieldEnum[]
}

/**
 * MaintenanceLog create
 */
export type MaintenanceLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceLog
   */
  select?: Prisma.MaintenanceLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceLog
   */
  omit?: Prisma.MaintenanceLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceLogInclude<ExtArgs> | null
  /**
   * The data needed to create a MaintenanceLog.
   */
  data: Prisma.XOR<Prisma.MaintenanceLogCreateInput, Prisma.MaintenanceLogUncheckedCreateInput>
}

/**
 * MaintenanceLog createMany
 */
export type MaintenanceLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MaintenanceLogs.
   */
  data: Prisma.MaintenanceLogCreateManyInput | Prisma.MaintenanceLogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MaintenanceLog createManyAndReturn
 */
export type MaintenanceLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceLog
   */
  select?: Prisma.MaintenanceLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceLog
   */
  omit?: Prisma.MaintenanceLogOmit<ExtArgs> | null
  /**
   * The data used to create many MaintenanceLogs.
   */
  data: Prisma.MaintenanceLogCreateManyInput | Prisma.MaintenanceLogCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceLogIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MaintenanceLog update
 */
export type MaintenanceLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceLog
   */
  select?: Prisma.MaintenanceLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceLog
   */
  omit?: Prisma.MaintenanceLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceLogInclude<ExtArgs> | null
  /**
   * The data needed to update a MaintenanceLog.
   */
  data: Prisma.XOR<Prisma.MaintenanceLogUpdateInput, Prisma.MaintenanceLogUncheckedUpdateInput>
  /**
   * Choose, which MaintenanceLog to update.
   */
  where: Prisma.MaintenanceLogWhereUniqueInput
}

/**
 * MaintenanceLog updateMany
 */
export type MaintenanceLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MaintenanceLogs.
   */
  data: Prisma.XOR<Prisma.MaintenanceLogUpdateManyMutationInput, Prisma.MaintenanceLogUncheckedUpdateManyInput>
  /**
   * Filter which MaintenanceLogs to update
   */
  where?: Prisma.MaintenanceLogWhereInput
  /**
   * Limit how many MaintenanceLogs to update.
   */
  limit?: number
}

/**
 * MaintenanceLog updateManyAndReturn
 */
export type MaintenanceLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceLog
   */
  select?: Prisma.MaintenanceLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceLog
   */
  omit?: Prisma.MaintenanceLogOmit<ExtArgs> | null
  /**
   * The data used to update MaintenanceLogs.
   */
  data: Prisma.XOR<Prisma.MaintenanceLogUpdateManyMutationInput, Prisma.MaintenanceLogUncheckedUpdateManyInput>
  /**
   * Filter which MaintenanceLogs to update
   */
  where?: Prisma.MaintenanceLogWhereInput
  /**
   * Limit how many MaintenanceLogs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceLogIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MaintenanceLog upsert
 */
export type MaintenanceLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceLog
   */
  select?: Prisma.MaintenanceLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceLog
   */
  omit?: Prisma.MaintenanceLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceLogInclude<ExtArgs> | null
  /**
   * The filter to search for the MaintenanceLog to update in case it exists.
   */
  where: Prisma.MaintenanceLogWhereUniqueInput
  /**
   * In case the MaintenanceLog found by the `where` argument doesn't exist, create a new MaintenanceLog with this data.
   */
  create: Prisma.XOR<Prisma.MaintenanceLogCreateInput, Prisma.MaintenanceLogUncheckedCreateInput>
  /**
   * In case the MaintenanceLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MaintenanceLogUpdateInput, Prisma.MaintenanceLogUncheckedUpdateInput>
}

/**
 * MaintenanceLog delete
 */
export type MaintenanceLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceLog
   */
  select?: Prisma.MaintenanceLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceLog
   */
  omit?: Prisma.MaintenanceLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceLogInclude<ExtArgs> | null
  /**
   * Filter which MaintenanceLog to delete.
   */
  where: Prisma.MaintenanceLogWhereUniqueInput
}

/**
 * MaintenanceLog deleteMany
 */
export type MaintenanceLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MaintenanceLogs to delete
   */
  where?: Prisma.MaintenanceLogWhereInput
  /**
   * Limit how many MaintenanceLogs to delete.
   */
  limit?: number
}

/**
 * MaintenanceLog.partsUsed
 */
export type MaintenanceLog$partsUsedArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartUsage
   */
  select?: Prisma.PartUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartUsage
   */
  omit?: Prisma.PartUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartUsageInclude<ExtArgs> | null
  where?: Prisma.PartUsageWhereInput
  orderBy?: Prisma.PartUsageOrderByWithRelationInput | Prisma.PartUsageOrderByWithRelationInput[]
  cursor?: Prisma.PartUsageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PartUsageScalarFieldEnum | Prisma.PartUsageScalarFieldEnum[]
}

/**
 * MaintenanceLog.photos
 */
export type MaintenanceLog$photosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Photo
   */
  select?: Prisma.PhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Photo
   */
  omit?: Prisma.PhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PhotoInclude<ExtArgs> | null
  where?: Prisma.PhotoWhereInput
  orderBy?: Prisma.PhotoOrderByWithRelationInput | Prisma.PhotoOrderByWithRelationInput[]
  cursor?: Prisma.PhotoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PhotoScalarFieldEnum | Prisma.PhotoScalarFieldEnum[]
}

/**
 * MaintenanceLog without action
 */
export type MaintenanceLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceLog
   */
  select?: Prisma.MaintenanceLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceLog
   */
  omit?: Prisma.MaintenanceLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceLogInclude<ExtArgs> | null
}
